return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "cpp",
      "c",
      "python",
      "glsl",
      "cmake",
      "make",
      "bash",
      "help",
      "html",
      "json",
      "java",
      "c_sharp",
      "lua",
      "markdown",
      "markdown_inline",
      "regex",
      "typescript",
      "vim",
      "yaml",
      "kotlin",
    },
  },
}
